"""
This type stub file was generated by pyright.
"""

from typing import List, Union

class Cubic:
    def __init__(self, curves: List[Union[float, int]]) -> None: ...
    def get_value(self, time: Union[float, int]):  # -> float:
        ...
    @staticmethod
    def calculate(a, b, m): ...

if __name__ == "__main__": ...
