"""
This type stub file was generated by pyright.
"""

from typing import List, Union

def interpolate(
    from_list: List[Union[float, int]],
    to_list: List[Union[float, int]],
    f: Union[float, int],
):  # -> list[Any]:
    ...
def interpolate_num(
    from_val: List[Union[float, int]],
    to_val: List[Union[float, int]],
    f: Union[float, int],
):  # -> list[float | int] | None:
    ...

if __name__ == "__main__": ...
