"""
This type stub file was generated by pyright.
"""

from typing import Union

def convert_rotation_to_matrix(rotation: Union[float, int]):  # -> list[float]:
    ...
def convertRotationToMatrix(degrees: Union[float, int]):  # -> list[Any]:
    ...

if __name__ == "__main__": ...
