"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, NamedTuple

from httpx import Response

from ..client.client import Client

if TYPE_CHECKING: ...

class UnlockHTML(NamedTuple):
    authenticity_token: str
    assignment_token: str
    needs_unlock: bool
    start_button: bool
    finish_button: bool
    delete_button: bool
    blob: str
    ...

class CaptchaSolver:
    client: Client
    max_attempts: int
    CAPTCHA_URL = ...
    CAPTCHA_SITE_KEY = ...
    async def get_unlock_html(self) -> tuple[Response, UnlockHTML]: ...
    async def ui_metrix(self) -> str: ...
    async def confirm_unlock(
        self,
        authenticity_token: str,
        assignment_token: str,
        verification_string: str = ...,
        ui_metrics: bool = ...,
    ) -> tuple[Response, UnlockHTML]: ...

def parse_unlock_html(html: str) -> UnlockHTML: ...
