"""
This type stub file was generated by pyright.
"""

from .base import CaptchaSolver

class Capsolver(CaptchaSolver):
    """
    You can automatically unlock the account by passing the `captcha_solver`
    argument when initialising the :class:`.Client`.

    First, visit https://capsolver.com and obtain your Capsolver API key.
    Next, pass the Capsolver instance to the client as shown in the example.

    .. code-block:: python

        from twikit.twikit_async import Capsolver, Client
        solver = Capsolver(
            api_key='your_api_key',
            max_attempts=10
        )
        client = Client(captcha_solver=solver)

    Parameters
    ----------
    api_key : :class:`str`
        Capsolver API key.
    max_attempts : :class:`int`, default=3
        The maximum number of attempts to solve the captcha.
    get_result_interval : :class:`float`, default=1.0

    use_blob_data : :class:`bool`, default=False
    """
    def __init__(
        self,
        api_key: str,
        max_attempts: int = ...,
        get_result_interval: float = ...,
        use_blob_data: bool = ...,
    ) -> None: ...
    def create_task(self, task_data: dict) -> dict: ...
    def get_task_result(self, task_id: str) -> dict: ...
    def solve_funcaptcha(self, blob: str) -> dict: ...
