"""
This type stub file was generated by pyright.
"""

import argparse
import httpx
from .models import Tweet, User

class CustomHelpFormatter(argparse.HelpFormatter):
    def __init__(self, prog) -> None:
        ...
    


def get_fn_arg(args): # -> tuple[str, Any]:
    ...

def to_str(doc: httpx.Response | Tweet | User | None) -> str:
    ...

async def main(args): # -> None:
    ...

def custom_help(p): # -> None:
    ...

def run(): # -> None:
    ...

