"""
This type stub file was generated by pyright.
"""

import aiosqlite
from collections import defaultdict

MIN_SQLITE_VERSION = ...
_lock = ...
def lock_retry(max_retries=...): # -> Callable[..., Callable[..., Coroutine[Any, Any, Any | None]]]:
    ...

async def get_sqlite_version(): # -> Any | Literal['3.0.0']:
    ...

async def check_version(): # -> None:
    ...

async def migrate(db: aiosqlite.Connection): # -> None:
    ...

class DB:
    _init_queries: defaultdict[str, list[str]] = ...
    _init_once: defaultdict[str, bool] = ...
    def __init__(self, db_path) -> None:
        ...
    
    async def __aenter__(self): # -> Connection:
        ...
    
    async def __aexit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    


@lock_retry()
async def execute(db_path: str, qs: str, params: dict | None = ...): # -> None:
    ...

@lock_retry()
async def fetchone(db_path: str, qs: str, params: dict | None = ...): # -> Row | None:
    ...

@lock_retry()
async def fetchall(db_path: str, qs: str, params: dict | None = ...): # -> Iterable[Row]:
    ...

@lock_retry()
async def executemany(db_path: str, qs: str, params: list[dict]): # -> None:
    ...

