"""
This type stub file was generated by pyright.
"""

import imaplib
from datetime import datetime

def env_int(key: str | list[str], default: int) -> int:
    ...

TWS_WAIT_EMAIL_CODE = ...
class EmailLoginError(Exception):
    def __init__(self, message=...) -> None:
        ...
    


class EmailCodeTimeoutError(Exception):
    def __init__(self, message=...) -> None:
        ...
    


IMAP_MAPPING: dict[str, str] = ...
def add_imap_mapping(email_domain: str, imap_domain: str): # -> None:
    ...

async def imap_get_email_code(imap: imaplib.IMAP4_SSL, email: str, min_t: datetime | None = ...) -> str:
    ...

async def imap_login(email: str, password: str): # -> IMAP4_SSL:
    ...

