"""
This type stub file was generated by pyright.
"""

from typing import Literal

_LEVELS = Literal["TRACE", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
_LOG_LEVEL: _LEVELS = ...
def set_log_level(level: _LEVELS): # -> None:
    ...

