"""
This type stub file was generated by pyright.
"""

import imaplib
from dataclasses import dataclass
from typing import Any
from httpx import AsyncClient, Response
from .account import Account

LOGIN_URL = ...
@dataclass
class LoginConfig:
    email_first: bool = ...
    manual: bool = ...


@dataclass
class TaskCtx:
    client: AsyncClient
    acc: Account
    cfg: LoginConfig
    prev: Any
    imap: None | imaplib.IMAP4_SSL
    ...


async def get_guest_token(client: AsyncClient): # -> Any:
    ...

async def login_initiate(client: AsyncClient) -> Response:
    ...

async def login_alternate_identifier(ctx: TaskCtx, *, username: str) -> Response:
    ...

async def login_instrumentation(ctx: TaskCtx) -> Response:
    ...

async def login_enter_username(ctx: TaskCtx) -> Response:
    ...

async def login_enter_password(ctx: TaskCtx) -> Response:
    ...

async def login_two_factor_auth_challenge(ctx: TaskCtx) -> Response:
    ...

async def login_duplication_check(ctx: TaskCtx) -> Response:
    ...

async def login_confirm_email(ctx: TaskCtx) -> Response:
    ...

async def login_confirm_email_code(ctx: TaskCtx): # -> Response:
    ...

async def login_success(ctx: TaskCtx) -> Response:
    ...

async def next_login_task(ctx: TaskCtx, rep: Response): # -> Response | None:
    ...

async def login(acc: Account, cfg: LoginConfig | None = ...) -> Account:
    ...

