"""
This type stub file was generated by pyright.
"""

from httpx import AsyncClient, Response
from .accounts_pool import Account, AccountsPool

ReqParams = dict[str, str | int] | None
TMP_TS = ...
class Ctx:
    def __init__(self, acc: Account, clt: AsyncClient) -> None:
        ...
    


class HandledError(Exception):
    ...


class AbortReqError(Exception):
    ...


def req_id(rep: Response): # -> str:
    ...

def dump_rep(rep: Response): # -> None:
    ...

class QueueClient:
    def __init__(self, pool: AccountsPool, queue: str, debug=..., proxy: str | None = ...) -> None:
        ...
    
    async def __aenter__(self): # -> Self:
        ...
    
    async def __aexit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    
    async def get(self, url: str, params: ReqParams = ...): # -> Response | None:
        ...
    
    async def req(self, method: str, url: str, params: ReqParams = ...) -> Response | None:
        ...
    


