"""
This type stub file was generated by pyright.
"""

import re

import js2py_

from .dom import MockDocument

FUNCTION_PATTERN = ...
EQUAL_PATTERN = ...

def solve_ui_metrics(ui_metrics: str) -> str: ...
