"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from httpx import Response

from .client.client import Client
from .tweet import Tweet
from .utils import Result

if TYPE_CHECKING: ...

class BookmarkFolder:
    """
    Attributes
    ----------
    id : :class:`str`
        The ID of the folder.
    name : :class:`str`
        The name of the folder
    media : :class:`str`
        Icon image data.
    """
    def __init__(self, client: Client, data: dict) -> None: ...
    async def get_tweets(self, cursor: str | None = ...) -> Result[Tweet]:
        """
        Retrieves tweets from the folder.
        """
        ...

    async def edit(self, name: str) -> BookmarkFolder:
        """
        Edits the folder.
        """
        ...

    async def delete(self) -> Response:
        """
        Deletes the folder.
        """
        ...

    async def add(self, tweet_id: str) -> Response:
        """
        Adds a tweet to the folder.
        """
        ...

    def __eq__(self, __value: object) -> bool: ...
    def __ne__(self, __value: object) -> bool: ...
    def __repr__(self) -> str: ...
